#4 - #6 Выполнены задачи четвертого и пятого модулей
js-tasks-ru/jsbasic-20220310_pelyuh-fedor pull request #4
Opened 2022-04-04 17:30 UTC by fPelyuh

2022-04-04 17:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-06 16:19 UTC, koalex requested changes
Исправить замечания и в 5-3 нужно чтобы стрелка влево пряталась при 0 слайде и стрелка вправо должна прятаться при последнем слайде

2022-04-06 16:19 UTC, koalex commented on 4-module/2-task/index.js
> +  const tableRow = document.querySelector('tr');
Заменить на `const tableRow = table.querySelector('tr');`

2022-04-06 16:19 UTC, koalex commented on 5-module/3-task/index.js
> +        carouselContainer.style.transform = `translate(-${slidesWidth[currentSlide + 1].translate}px)`;
`translate` заменить на `translateX`

2022-04-06 16:19 UTC, koalex commented on 5-module/3-task/index.js
> +        carouselContainer.style.transform = `translate(0px)`;
`translate` заменить на `translateX`

2022-04-06 16:19 UTC, koalex commented on 5-module/3-task/index.js
> +        carouselContainer.style.transform = `translate(-${slidesWidth[lastSlide].translate}px)`;
`translate` заменить на `translateX`

2022-04-06 16:19 UTC, koalex commented on 5-module/3-task/index.js
> +        carouselContainer.style.transform = `translate(-${slidesWidth[currentSlide].translate}px)`;
`translate` заменить на `translateX`

2022-04-06 16:19 UTC, koalex commented on 5-module/3-task/index.js
> +      carouselContainer.style.transform = `translate(-${slidesWidth[currentSlide].translate}px)`;
`translate` заменить на `translateX`

2022-04-07 18:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-04-08 11:17 UTC, koalex approved these changes

2022-04-08 11:18 UTC, merged